"""SQLAlchemy ORM models.

One table for now: jobs. JSON columns hold the Pydantic payloads
(TripRequest on the way in, TripPlan on the way out) so the API contract
stays defined by app/models.py — the DB never invents its own schema for
what a trip looks like.
"""

from datetime import datetime, timezone

from sqlalchemy import JSON, DateTime, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class JobRow(Base):
    __tablename__ = "jobs"

    # 12-hex-char id generated by the API layer (same shape as before).
    job_id: Mapped[str] = mapped_column(String(32), primary_key=True)
    # pending → running → complete | failed. Stored as plain text; the API
    # maps it back onto models.JobStatus so the contract stays Pydantic.
    status: Mapped[str] = mapped_column(String(16), nullable=False,
                                       default="pending", index=True)
    # The original request — replayable/debuggable without re-asking the user.
    request_json: Mapped[dict] = mapped_column(JSON, nullable=False)
    # The ranked plan once complete; NULL until then.
    plan_json: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    # Human-readable failure cause; NULL unless failed.
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Python-side timestamps: explicit and dialect-proof (SQLite has no
    # TIMESTAMPTZ). Always UTC.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow)
